// Search Index - Lists of unique symptoms and diseases for dropdowns

const SYMPTOMS_LIST = [
    "Abdominal distension",
    "Abdominal pain",
    "Acid regurgitation",
    "Agitation",
    "Ankle pain",
    "Anorexia",
    "Anxiety",
    "Arm pain",
    "Asthma",
    "Back pain",
    "Belching",
    "Bitter taste",
    "Bloating",
    "Blurred vision",
    "Breast distension",
    "Breast pain",
    "Breathlessness",
    "Burning urination",
    "Chest oppression",
    "Chest pain",
    "Chills",
    "Cold extremities",
    "Cold limbs",
    "Constipation",
    "Cough",
    "Cramping",
    "Deafness",
    "Depression",
    "Diarrhea",
    "Difficulty breathing",
    "Difficulty swallowing",
    "Dizziness",
    "Dream-disturbed sleep",
    "Drowsiness",
    "Dry cough",
    "Dry eyes",
    "Dry mouth",
    "Dry skin",
    "Dry throat",
    "Dyspnea",
    "Ear pain",
    "Edema",
    "Elbow pain",
    "Emotional instability",
    "Epigastric pain",
    "Excessive dreaming",
    "Excessive salivation",
    "Eye pain",
    "Eye redness",
    "Facial pain",
    "Facial paralysis",
    "Fatigue",
    "Fear",
    "Fever",
    "Finger numbness",
    "Flatulence",
    "Floaters",
    "Flushed face",
    "Foot pain",
    "Forgetfulness",
    "Frequent urination",
    "Fullness sensation",
    "Gastric pain",
    "Hand numbness",
    "Hand tremors",
    "Headache",
    "Hearing loss",
    "Heartburn",
    "Heat sensation",
    "Heavy limbs",
    "Hematemesis",
    "Hematuria",
    "Hemorrhoids",
    "Hiccups",
    "Hip pain",
    "Hoarseness",
    "Hot flashes",
    "Hypochondriac pain",
    "Impotence",
    "Inability to concentrate",
    "Incontinence",
    "Indigestion",
    "Insomnia",
    "Intercostal neuralgia",
    "Irritability",
    "Itching",
    "Jaundice",
    "Jaw pain",
    "Joint pain",
    "Knee pain",
    "Lacrimation",
    "Leg cramps",
    "Leg pain",
    "Lethargy",
    "Light-headedness",
    "Limb weakness",
    "Loose stools",
    "Loss of appetite",
    "Low back pain",
    "Lower abdominal pain",
    "Lumbar pain",
    "Mania",
    "Memory loss",
    "Menstrual cramps",
    "Mental confusion",
    "Migraine",
    "Mood swings",
    "Mouth sores",
    "Muscle aches",
    "Muscle cramps",
    "Muscle spasms",
    "Muscle stiffness",
    "Muscle weakness",
    "Nasal congestion",
    "Nasal discharge",
    "Nausea",
    "Neck pain",
    "Neck stiffness",
    "Nervousness",
    "Night sweats",
    "Nightmares",
    "Nipple pain",
    "Nocturia",
    "Nose bleeding",
    "Numbness",
    "Oliguria",
    "Painful intercourse",
    "Painful menstruation",
    "Palpitations",
    "Panic attacks",
    "Paralysis",
    "Paresthesia",
    "Pelvis pain",
    "Photophobia",
    "Poor appetite",
    "Poor circulation",
    "Poor concentration",
    "Poor memory",
    "Profuse sweating",
    "Pruritus",
    "Rapid heartbeat",
    "Rash",
    "Red eyes",
    "Restlessness",
    "Rhinitis",
    "Rib-side pain",
    "Ringing in ears",
    "Runny nose",
    "Sciatica",
    "Seizures",
    "Sensitivity to cold",
    "Sensitivity to light",
    "Shaking",
    "Shin pain",
    "Shortness of breath",
    "Shoulder pain",
    "Sinusitis",
    "Skin eruptions",
    "Skin itching",
    "Sleepiness",
    "Sneezing",
    "Sore throat",
    "Spasms",
    "Stiff neck",
    "Stiffness",
    "Stomach ache",
    "Stress",
    "Sweating",
    "Swelling",
    "Swollen glands",
    "Tardy digestion",
    "Temporal headache",
    "Tender breasts",
    "Thigh pain",
    "Thirst",
    "Throat discomfort",
    "Throat pain",
    "Throat swelling",
    "Tinnitus",
    "Toe pain",
    "Tongue swelling",
    "Toothache",
    "Trembling",
    "Tremors",
    "Ulcers",
    "Upper back pain",
    "Urinary difficulty",
    "Urinary frequency",
    "Urinary retention",
    "Urticaria",
    "Uterine bleeding",
    "Vaginal discharge",
    "Vaginal dryness",
    "Vaginal itching",
    "Vertigo",
    "Visual disturbances",
    "Vomiting",
    "Watery eyes",
    "Weakness",
    "Weight loss",
    "Wheezing",
    "Wrist pain",
    "Yellow eyes",
    "Yellow urine",
    "Appetite loss",
    "Blood in stool",
    "Blood in urine",
    "Body aches",
    "Burning eyes",
    "Burning sensation",
    "Chest congestion",
    "Chest tightness",
    "Chronic cough",
    "Cloudy urine",
    "Cognitive impairment",
    "Cold hands",
    "Cold feet",
    "Cracked lips",
    "Dark circles under eyes",
    "Dark urine",
    "Decreased libido",
    "Delayed menstruation",
    "Digestive discomfort",
    "Dilated pupils",
    "Distended abdomen",
    "Disturbed sleep",
    "Dry hair",
    "Dry lips",
    "Dysmenorrhea",
    "Ear discharge",
    "Early menstruation",
    "Emotional stress",
    "Excessive gas",
    "Excessive hunger",
    "Excessive thirst",
    "Eye discharge",
    "Eye fatigue",
    "Eye strain",
    "Facial flushing",
    "Facial swelling",
    "Fainting",
    "Feeling cold",
    "Feeling hot",
    "Fibromyalgia pain",
    "Frequent colds",
    "Frequent infections",
    "Genital itching",
    "Genital pain",
    "Grinding teeth",
    "Gum bleeding",
    "Hair loss",
    "Hand coldness",
    "Hard stools",
    "Heavy head",
    "Heavy menstruation",
    "Hypersomnia",
    "Hypertension symptoms",
    "Increased appetite",
    "Inflammation",
    "Inner restlessness",
    "Intestinal cramping",
    "Irregular heartbeat",
    "Irregular menstruation",
    "Joint stiffness",
    "Joint swelling",
    "Kidney pain",
    "Lack of energy",
    "Lack of strength",
    "Leg numbness",
    "Leg swelling",
    "Light menstruation",
    "Liver discomfort",
    "Loss of consciousness",
    "Lymph node swelling",
    "Mastitis pain",
    "Menstrual irregularity",
    "Mental fatigue",
    "Metallic taste",
    "Migraine aura",
    "Mild fever",
    "Mouth dryness",
    "Mouth ulcers",
    "Mucus in stool",
    "Muscle tension",
    "Muscle twitching",
    "Nail problems",
    "Nasal blockage",
    "Neck tension",
    "Nerve pain",
    "Night blindness",
    "Occipital headache",
    "Oral thrush",
    "Ovarian pain",
    "Pain during urination",
    "Pale complexion",
    "Pale lips"
];

const DISEASES_LIST = [
    "Acne",
    "Acute gastritis",
    "Allergic rhinitis",
    "Alzheimer's disease",
    "Amenorrhea",
    "Anemia",
    "Angina",
    "Ankle sprain",
    "Anorexia nervosa",
    "Anxiety disorder",
    "Appendicitis",
    "Arrhythmia",
    "Arthritis",
    "Asthma",
    "Atopic dermatitis",
    "Atrial fibrillation",
    "Autoimmune disorders",
    "Back strain",
    "Bell's palsy",
    "Benign prostatic hyperplasia",
    "Bipolar disorder",
    "Bladder infection",
    "Blepharitis",
    "Bloating syndrome",
    "Bronchial asthma",
    "Bronchitis",
    "Bursitis",
    "Cancer pain",
    "Candidiasis",
    "Carpal tunnel syndrome",
    "Cataracts",
    "Celiac disease",
    "Cerebral palsy",
    "Cervical spondylosis",
    "Cholecystitis",
    "Chronic bronchitis",
    "Chronic cough",
    "Chronic fatigue syndrome",
    "Chronic gastritis",
    "Chronic headache",
    "Chronic hepatitis",
    "Chronic kidney disease",
    "Chronic obstructive pulmonary disease",
    "Chronic pain",
    "Chronic sinusitis",
    "Cirrhosis",
    "Colitis",
    "Common cold",
    "Conjunctivitis",
    "Constipation",
    "Coronary artery disease",
    "Costochondritis",
    "Cough variant asthma",
    "Crohn's disease",
    "Cystitis",
    "Dementia",
    "Depression",
    "Dermatitis",
    "Diabetes mellitus",
    "Diabetic neuropathy",
    "Diarrhea",
    "Diverticulitis",
    "Drug addiction",
    "Dry eye syndrome",
    "Duodenal ulcer",
    "Dysmenorrhea",
    "Dyspepsia",
    "Eczema",
    "Edema",
    "Elbow tendinitis",
    "Emphysema",
    "Endometriosis",
    "Epilepsy",
    "Erectile dysfunction",
    "Esophageal reflux",
    "Facial neuralgia",
    "Fibrocystic breast disease",
    "Fibromyalgia",
    "Flatulence",
    "Flu",
    "Frozen shoulder",
    "Gallstones",
    "Gastric ulcer",
    "Gastritis",
    "Gastroenteritis",
    "Gastroesophageal reflux disease",
    "Genital herpes",
    "Glaucoma",
    "Gout",
    "Graves' disease",
    "Headache",
    "Heart disease",
    "Heartburn",
    "Hemorrhoids",
    "Hepatitis",
    "Herniated disc",
    "Herpes zoster",
    "Hiatal hernia",
    "High blood pressure",
    "Hip arthritis",
    "Hives",
    "Hyperacidity",
    "Hypercholesterolemia",
    "Hyperlipidemia",
    "Hypertension",
    "Hyperthyroidism",
    "Hypoglycemia",
    "Hypothyroidism",
    "Impotence",
    "Incontinence",
    "Indigestion",
    "Infertility",
    "Inflammatory bowel disease",
    "Influenza",
    "Insomnia",
    "Intercostal neuralgia",
    "Interstitial cystitis",
    "Irregular menstruation",
    "Irritable bowel syndrome",
    "Ischemic heart disease",
    "Jaundice",
    "Kidney stones",
    "Knee arthritis",
    "Knee osteoarthritis",
    "Labor pain",
    "Lactose intolerance",
    "Laryngitis",
    "Leg cramps",
    "Leukorrhea",
    "Lower back pain",
    "Lumbar disc disease",
    "Lumbar sprain",
    "Lumbago",
    "Lung cancer",
    "Lupus",
    "Lyme disease",
    "Lymphedema",
    "Macular degeneration",
    "Malaria",
    "Mastitis",
    "Meniere's disease",
    "Menopausal syndrome",
    "Menopause",
    "Menorrhagia",
    "Menstrual disorders",
    "Migraine",
    "Morning sickness",
    "Motion sickness",
    "Multiple sclerosis",
    "Mumps",
    "Muscle strain",
    "Myasthenia gravis",
    "Myocardial infarction",
    "Myofascial pain syndrome",
    "Myopia",
    "Narcolepsy",
    "Nasal polyps",
    "Nausea",
    "Neck pain",
    "Nephritis",
    "Nerve damage",
    "Neuralgia",
    "Neurosis",
    "Neuropathy",
    "Night sweats",
    "Obesity",
    "Obsessive-compulsive disorder",
    "Osteoarthritis",
    "Osteoporosis",
    "Otitis media",
    "Ovarian cysts",
    "Pain syndrome",
    "Pancreatitis",
    "Panic disorder",
    "Paralysis",
    "Parkinson's disease",
    "Pelvic inflammatory disease",
    "Peptic ulcer",
    "Peripheral neuropathy",
    "Pharyngitis",
    "Plantar fasciitis",
    "Pleurisy",
    "Pneumonia",
    "Polycystic ovary syndrome",
    "Post-traumatic stress disorder",
    "Postpartum depression",
    "Premenstrual syndrome",
    "Prostate enlargement",
    "Prostatitis",
    "Psoriasis",
    "Psychosis",
    "Pulmonary disease",
    "Raynaud's disease",
    "Renal failure",
    "Restless leg syndrome",
    "Rheumatism",
    "Rheumatoid arthritis",
    "Rhinitis",
    "Rosacea",
    "Rotator cuff injury",
    "Scabies",
    "Schizophrenia",
    "Sciatica",
    "Seasonal allergies",
    "Seizure disorder",
    "Shingles",
    "Shoulder bursitis",
    "Shoulder impingement",
    "Shoulder pain",
    "Sinusitis",
    "Skin disorders",
    "Sleep apnea",
    "Sore throat",
    "Spinal stenosis",
    "Sprains",
    "Stomach flu",
    "Stress disorders",
    "Stroke",
    "Substance abuse",
    "Swimmer's ear",
    "Temporomandibular joint disorder",
    "Tendinitis",
    "Tennis elbow",
    "Tension headache",
    "Thoracic outlet syndrome",
    "Thrombosis",
    "Thyroid disorders",
    "Tinnitus",
    "Tonsillitis",
    "Toothache",
    "Torticollis",
    "Tremor",
    "Trigeminal neuralgia",
    "Tuberculosis",
    "Ulcerative colitis",
    "Urethritis",
    "Urinary incontinence",
    "Urinary retention",
    "Urinary tract infection",
    "Urticaria",
    "Uterine fibroids",
    "Uterine prolapse",
    "Vaginitis",
    "Varicose veins",
    "Vasculitis",
    "Vertigo",
    "Viral hepatitis",
    "Vitiligo",
    "Vomiting",
    "Warts",
    "Whiplash",
    "Whooping cough",
    "Wrist sprain"
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { SYMPTOMS_LIST, DISEASES_LIST };
}